ffmpeg:
  # FFmpeg executable path (update this to your actual FFmpeg installation path)
  ffmpeg-path: E:\ffmpeg-7.1-full_build\bin\ffmpeg.exe
  # FFprobe executable path
  ffprobe-path: E:\ffmpeg-7.1-full_build\bin\ffprobe.exe
  # Output directory for transcoded files
  output-path: E:\transcoded
  # Temporary directory for processing
  temp-path: E:\temp
  # HLS segment duration in seconds
  hls-time: 10
  # HLS playlist size (0 means keep all segments)
  hls-list-size: 0
  # Video bitrates for different qualities (in kbps)
  video-bitrates: [800, 1400, 2800]  # 480p, 720p, 1080p
  # Video resolutions (height in pixels)
  video-resolutions: [480, 720, 1080]
